[package]
name = "portfu_updated"
version = "2.0.0"
edition = "2024"

[dependencies]
http = "1.4.0"
http-body = "1.0.1"
http-body-util = { version = "0.1.3"}
futures-util = "0.3.31"
inventory = "0.3.21"
hyper = {version = "1.8.1", features = ["server", "client", "http1", "http2"] }
portfu_common = {path="../portfu_common"}
portfu_macros_updated = {path="../portfu_macros_updated"}
tokio = {version = "1.47.1", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}
regex = "1.12.3"
hyper-util = {version = "0.1.20", features = ["tokio"]}
tokio-tungstenite = "0.28.0"
rustls = "0.23.20"
tokio-rustls = "0.26.1"
webpki-roots = "1.0.6"
log = "0.4.29"
