[package]
name = "portfu_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
http = "1.1.0"
http-body-util = { version = "0.1"}
hyper = {version="1.2.0", features=["full"]}
regex = { version = "1.10.2", features = [] }
once_cell = "1.19.0"