[package]
name = "portfu_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
log.workspace = true
once_cell.workspace = true
regex.workspace = true
serde_json.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
uuid.workspace = true