[package]
name = "portfu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.77"
futures-util = "0.3.30"
http = "1.1.0"
http-body-util = { version = "0.1"}
hyper-util = {version="0.1.3", features=["full"]}
hyper = {version="1.2.0", features=["full"]}
portfu_core = {path = "../portfu_core"}
portfu_macros = {path = "../portfu_macros"}
tokio = {version = "1.36.0", features=["rt-multi-thread", "sync", "signal", "macros", "process", "time", "fs", "net"]}
serde = { version = "1.0.197", features = ["derive"] }
rustls = "0.22.2"
rustls-pemfile = "2.1.1"
x509-cert = "0.2.5"
log = "0.4.21"
tokio-rustls = "0.25.0"
