[package]
name = "portfu"
version = "2.0.0"
edition = "2024"

[features]
default = ["full"]
full = [
    "client",
    "cors",
    "endpoint",
    "files",
    "maud",
    "metrics",
    "oauth",
    "rate-limit",
    "sessions",
    "tasks",
    "tls",
    "websocket",
]
client = [
    "dep:rustls",
    "dep:tokio-tungstenite",
    "dep:tokio-rustls",
    "dep:webpki-roots",
    "hyper/client",
    "portfu_common/client",
    "portfu_common/websocket",
    "portfu_macros/client",
]
cors = ["portfu_common/cors"]
endpoint = ["portfu_macros/endpoint"]
files = ["portfu_common/files", "portfu_macros/files"]
maud = ["dep:maud", "portfu_macros/maud"]
metrics = ["portfu_common/metrics"]
oauth = ["portfu_common/oauth"]
rate-limit = ["portfu_common/rate-limit"]
sessions = ["portfu_common/sessions"]
tasks = ["portfu_common/tasks", "portfu_macros/tasks"]
tls = ["dep:rustls", "dep:tokio-rustls", "portfu_common/tls"]
websocket = ["dep:tokio-tungstenite", "portfu_common/websocket", "portfu_macros/websocket"]

[dependencies]
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
futures-util = { workspace = true }
inventory = { workspace = true }
hyper = { workspace = true, features = ["server", "http1", "http2"] }
portfu_common = {path="../portfu_common", default-features = false}
portfu_macros = {path="../portfu_macros", default-features = false}
tokio = { workspace = true }
regex = { workspace = true }
hyper-util = { workspace = true, features = ["tokio"]}
maud = { workspace = true, optional = true }
tokio-tungstenite = { workspace = true, optional = true }
uuid = { workspace = true }
rustls = { workspace = true, optional = true }
tokio-rustls = { workspace = true, optional = true }
webpki-roots = { workspace = true, optional = true }
log = { workspace = true }
