[package]
name = "portfu_macros"
version = "2.0.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = ["full"]
full = ["client", "endpoint", "files", "maud", "tasks", "websocket"]
client = ["websocket"]
endpoint = []
files = []
maud = ["endpoint"]
tasks = []
websocket = ["endpoint"]

[dependencies]
portfu_common = {path="../portfu_common", default-features = false}
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
