[package]
name = "portfu_macros"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
async-trait = "0.1.77"
http = "1.1.0"
http-body-util = { version = "0.1"}
hyper = {version="1.2.0", features=["full"]}
portfu_core = {path = "../portfu_core"}
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = "2.0.52"
