[package]
name = "portfu_macros"
version = "2.0.0"
edition = "2021"

[lib]
proc-macro = true

[features]
default = ["full"]
full = ["client", "endpoint", "files", "tasks", "websocket"]
client = ["websocket"]
endpoint = []
files = []
tasks = []
websocket = ["endpoint"]

[dependencies]
portfu_common = {path="../portfu_common", default-features = false}
proc-macro2 = "1.0.101"
quote = "1.0.40"
syn = { version="2.0.106", features = ["extra-traits"]}
